version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TODOAPP_PORT=8080
      - TODOAPP_CONNECTIONSTRING="host=localhost user=golang password=123 dbname=tododb port=20002"
      - TODOAPP_MIGRATE=true
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tododb