version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TODOAPP_PORT=8080
      - TODOAPP_CONNECTIONSTRING=host=db user=golang password=123 dbname=tododb port=5432
      - TODOAPP_MIGRATE=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    entrypoint: docker-entrypoint.sh -c max_connections=10000
    environment:
      - POSTGRES_USER=golang
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tododb
    healthcheck:
      test: pg_isready -d tododb -U golang