@url = http://localhost:8080

### Create
POST {{url}}/api/todos
Content-Type: application/json

{
  "title": "Test",
  "description": "Some description to test",
  "deadlineAt": "2024-04-20T13:01:16.194308Z"
}

### Get all
GET {{url}}/api/todos/
Accept: application/json

### Mark as done
DELETE {{url}}/api/todos/3

